export const GAME_WIDTH = 15;
export const GAME_HEIGHT = 25;
export const BLOCK_WIDTH = 20;
export const SHADOW_WIDTH = 3;
export const DELAY = 10;
export const DROP_INTERVAL_DEFAULT = 300;
export const DROP_INTERVAL_MIN = 30;
export const DROP_INTERVAL_DECREMENT = 20;
export const DROP_INTERVAL_ACCELERATING = 30;
export const LINE_CLEAR_BONUS = [100, 200, 300, 400];
export const UP = 38; // up arrow, and so on
export const LEFT = 37;
export const RIGHT = 39;
export const DOWN = 40;
export const PAUSE = 80; // letter p
export const START = 83; // letter s
